# Generated by Django 2.2.5 on 2019-09-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0011_auto_20190918_0023'),
        ('signup', '0004_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='virtual_env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envirnment_name', models.CharField(default='', max_length=250)),
                ('install_dir', models.CharField(default='', max_length=250)),
                ('python_inter_full', models.CharField(default='', max_length=250)),
                ('python_inter', models.CharField(default='', max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user')),
            ],
        ),
    ]
