# Generated by Django 2.2.5 on 2019-09-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtual_env',
            name='status',
            field=models.CharField(default='', max_length=250),
        ),
    ]
