# Generated by Django 2.2.5 on 2019-09-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_projects'),
        ('lamp', '0006_ftp_account'),
        ('servers', '0011_auto_20190918_0023'),
        ('django_auto', '0002_virtual_env_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_auto.virtual_env')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamp.domain')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user')),
            ],
        ),
    ]
