# Generated by Django 2.2.5 on 2019-10-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadBalancer', '0002_config_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='monitor_pass',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='config',
            name='monitor_user',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
