# Generated by Django 2.2.5 on 2019-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadBalancer', '0003_auto_20191007_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='header',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
