# Generated by Django 2.2.5 on 2019-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadBalancer', '0004_config_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='header',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='monitor_pass',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='monitor_user',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
