# Generated by Django 2.2.5 on 2019-10-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadBalancer', '0006_config_node_servers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='date',
        ),
        migrations.RemoveField(
            model_name='config',
            name='header',
        ),
        migrations.RemoveField(
            model_name='config',
            name='label',
        ),
        migrations.RemoveField(
            model_name='config',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='config',
            name='monitor_pass',
        ),
        migrations.RemoveField(
            model_name='config',
            name='monitor_user',
        ),
        migrations.RemoveField(
            model_name='config',
            name='node_servers',
        ),
        migrations.RemoveField(
            model_name='config',
            name='status',
        ),
        migrations.RemoveField(
            model_name='config',
            name='sub_dic',
        ),
    ]
