# Generated by Django 2.2.5 on 2019-10-07 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loadBalancer', '0007_auto_20191007_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='header',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='monitor_pass',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='monitor_user',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='node_servers',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='status',
            field=models.CharField(default='Configuring', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='sub_dic',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
