# Generated by Django 2.2.5 on 2019-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadBalancer', '0008_auto_20191007_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='sub_dic',
        ),
        migrations.AddField(
            model_name='config',
            name='algorithm',
            field=models.CharField(default='Round Robin', max_length=45),
        ),
    ]
