# Generated by Django 2.2.5 on 2019-10-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_projects'),
        ('servers', '0027_auto_20191007_2324'),
        ('loadBalancer', '0010_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='replicate_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('subdomain', models.CharField(default='', max_length=100)),
                ('folder', models.CharField(default='', max_length=100)),
                ('status', models.CharField(max_length=45)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('connected_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadBalancer.domains')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user')),
            ],
        ),
    ]
