# Generated by Django 2.2.5 on 2019-10-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadBalancer', '0011_replicate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replicate_file',
            name='subdomain',
        ),
    ]
