# Generated by Django 2.2.5 on 2019-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=45)),
                ('distribution_id', models.IntegerField()),
                ('stack_id', models.IntegerField()),
                ('ServerType', models.CharField(choices=[('MASTER', 'MASTER'), ('SLAVE', 'SLAVE')], default='MASTER', max_length=25)),
                ('server_status', models.CharField(max_length=45)),
                ('running_status', models.CharField(max_length=45)),
            ],
        ),
    ]
