# Generated by Django 2.2.5 on 2019-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='JSON_PKG_LST',
            field=models.TextField(default='{}'),
        ),
    ]
