# Generated by Django 2.2.5 on 2019-09-08 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20190907_1331'),
        ('servers', '0002_list_json_pkg_lst'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='list',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='stack_name',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='list',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signup.user'),
            preserve_default=False,
        ),
    ]
