# Generated by Django 2.2.5 on 2019-09-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20190908_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
    ]
