# Generated by Django 2.2.5 on 2019-09-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='command',
            field=models.CharField(default='', max_length=250),
        ),
    ]
