# Generated by Django 2.2.5 on 2019-10-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_auto_20191007_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='distribution_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='stack_id',
            field=models.IntegerField(default=0),
        ),
    ]
