# Generated by Django 2.2.5 on 2019-10-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0015_auto_20191007_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='parent_server',
            field=models.IntegerField(default=0),
        ),
    ]
