# Generated by Django 2.2.5 on 2019-10-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0016_auto_20191007_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='distribution_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='parent_server',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.list'),
        ),
        migrations.AlterField(
            model_name='list',
            name='stack_id',
            field=models.IntegerField(),
        ),
    ]
