# Generated by Django 2.2.5 on 2019-10-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0019_list_hostname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='hostname',
            new_name='server_hostname',
        ),
    ]
