# Generated by Django 2.2.5 on 2019-10-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0020_auto_20191007_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='server_hostname',
            new_name='hostname',
        ),
    ]
