# Generated by Django 2.2.5 on 2019-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0023_auto_20191007_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='parent_server',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
