# Generated by Django 2.2.5 on 2019-10-16 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0029_remove_server_stats_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('icon', models.CharField(default='', max_length=20)),
                ('color', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.list')),
            ],
        ),
    ]
