# Generated by Django 2.2.5 on 2019-09-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250)),
                ('email_verify', models.BooleanField(default=False)),
                ('email_hash', models.CharField(max_length=100)),
                ('contry_code', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('phone_otp', models.IntegerField()),
                ('phone_verify', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=75)),
                ('money', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gstin', models.CharField(max_length=75)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=75)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(max_length=25)),
                ('isPrimary', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user')),
            ],
        ),
    ]
