# Generated by Django 2.2.5 on 2019-09-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20190907_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
