# Generated by Django 2.2.5 on 2019-10-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.CreateModel(
            name='transation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('transation_id', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.user')),
            ],
        ),
    ]
