# Generated by Django 2.2.5 on 2019-10-16 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_auto_20191016_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='transation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
